name: README

on:
schedule: # Runs at 12am IST - cron: '30 18 \* \* \*'
workflow_dispatch:
jobs:
update-readme:
name: Update Readme with Metrics
runs-on: ubuntu-latest
steps: - uses: athul/waka-readme@master # this action name
with:
WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
GH_TOKEN: ${{ secrets.GH_TOKEN }}
SHOW_OS: "False"
SHOW_PROJECTS: "False"
SECTION_NAME: "Progress Tracker"
SHOW_UPDATED_DATE : "True"
SHOW_DAYS_OF_WEEK : "False"
SHOW_PROJECTS : "False"
SHOW_LANGUAGE_PER_REPO: "False"
SHOW_LOC_CHART: "False"
